			["!!1", !!1],
			["!!0", !!0],
			["!!-0", !!-0],
			["!!NaN", !!NaN],
			["!!Infinity", !!Infinity],
			["!!undefined", !!undefined],
			["!!null", !!null],
			["!!0n", !!0n],
			["!!'test'", !!'test'],
			["!!''", !!''],
			["!!{}", !!{}],
			["!![]", !![]],
			["!!Symbol()", !!Symbol()],
			["!!(()=>{})", !!(()=>{})],
			["!!(function(){})", !!(function(){})],
			["!!LanguageNames.en_us", !!LanguageNames.en_us],
			["!!LanguageNames.zh_cn", !!LanguageNames.zh_cn],

			["<boolean> <unknown> 1", <boolean> <unknown> 1],
			["<boolean> <unknown> 0", <boolean> <unknown> 0],

			["1 as unknown as boolean", 1 as unknown as boolean],
			["0 as unknown as boolean", 0 as unknown as boolean],

			["true === 1 as unknown as boolean", true === 1 as unknown as boolean],
			["true == 1 as unknown as boolean", true == 1 as unknown as boolean],

			["false === 0 as unknown as boolean", false === 0 as unknown as boolean],
			["false == 0 as unknown as boolean", false == 0 as unknown as boolean],

			["undefined as unknown as boolean", undefined as unknown as boolean],
			["null as unknown as boolean", null as unknown as boolean],

			["'test' as unknown as boolean", 'test' as unknown as boolean],
			["'' as unknown as boolean", '' as unknown as boolean],

			["{} as unknown as boolean", {} as unknown as boolean],
			["[] as unknown as boolean", [] as unknown as boolean],

			["LanguageNames.en_us as unknown as boolean", LanguageNames.en_us as unknown as boolean],
			["LanguageNames.zh_cn as unknown as boolean", LanguageNames.zh_cn as unknown as boolean],


			["1", 1],
			["0", 0],
			["-0", -0],
			["NaN", NaN],
			["Infinity", Infinity],
			["undefined", undefined],
			["null", null],
			["0n", 0n],
			["'test'", 'test'],
			["''", ''],
			["{}", {}],
			["[]", []],
			["Symbol()", Symbol()],
			["(()=>{})", (()=>{})],
			["(function(){})", (function(){})],
			["LanguageNames.en_us", LanguageNames.en_us],
			["LanguageNames.zh_cn", LanguageNames.zh_cn],
