			[1, 1],
			[0, 0],
			[-0, -0],
			[NaN, NaN],
			[Infinity, Infinity],
			[undefined, undefined],
			[null, null],
			[0n, 0n],
			['test', 'test'],
			['', ''],
			[{}, {}],
			[[], []],
			[Symbol(), Symbol()],
			[(()=>{}), (()=>{})],
			[(function(){}), (function(){})],
			[LanguageNames.en_us, LanguageNames.en_us],
			[LanguageNames.zh_cn, LanguageNames.zh_cn],
			[true, true],
			[false, false],
			[new Boolean(true), new Boolean(true)],
			[new Boolean(false), new Boolean(false)],
