			["0b10", 0b10],
			["0o76543210", 0o76543210],
			["9876543210", 9876543210],
			["0xFEDCBA9876543210", 0xFEDCBA9876543210],
			["Number.MIN_VALUE", Number.MIN_VALUE],
			["Number.MIN_SAFE_INTEGER", Number.MIN_SAFE_INTEGER],
			["Number.MAX_VALUE", Number.MAX_VALUE],
			["Number.MAX_SAFE_INTEGER", Number.MAX_SAFE_INTEGER],
			["NaN", NaN],
			["Infinity", Infinity],
			["-Infinity", -Infinity],
			["Math.E", Math.E],
			["Math.LN10", Math.LN10],
			["Math.LN2", Math.LN2],
			["Math.LOG2E", Math.LOG2E],
			["Math.LOG10E", Math.LOG10E],
			["Math.PI", Math.PI],
			["Math.SQRT1_2", Math.SQRT1_2],
			["Math.SQRT2", Math.SQRT2],

			["'0'", '0'],
			["'1'", '1'],
			["'0b10'", '0b10'],
			["'0o10'", '0o10'],
			["'0x10'", '0x10'],
			["true", true],
			["false", false],
			["undefined", undefined],
			["null", null],
			["{}", {}],
			["[]", []],
			["LanguageNames.en_us", LanguageNames.en_us],
			["LanguageNames.zh_cn", LanguageNames.zh_cn],
			["LanguageNames.zh_tw", LanguageNames.zh_tw],
			["'      123      \\n    '", '      123      \n    '],
			["''", ''],
			["'   '", '   '],
			["'1,234'", '1,234'],
			["'+123'", '+123'],
			["'-123'", '-123'],
			["'++123'", '++123'],
			["'--123'", '--123'],
			["'+ 123'", '+ 123'],
			["'- 123'", '- 123'],
			["NaN", NaN],
			["Infinity", Infinity],
			["-Infinity", -Infinity],
			["'0123'", '0123'],
			["10n", 10n],

			["Symbol()", Symbol()],




			["Number.prototype", Number.prototype],
			["Number.EPSILON", Number.EPSILON],
			["Number.MAX_SAFE_INTEGER", Number.MAX_SAFE_INTEGER],
			["Number.MIN_SAFE_INTEGER", Number.MIN_SAFE_INTEGER],
			["Number.MAX_VALUE", Number.MAX_VALUE],
			["Number.MIN_VALUE", Number.MIN_VALUE],
			["Number.NaN", Number.NaN],
			["Number.NEGATIVE_INFINITY", Number.NEGATIVE_INFINITY],
			["Number.POSITIVE_INFINITY", Number.POSITIVE_INFINITY],

			["Number.isFinite", Number.isFinite],
			["Number.isInteger", Number.isInteger],
			["Number.isNaN", Number.isNaN],
			["Number.isSafeInteger", Number.isSafeInteger],
			["Number.parseFloat", Number.parseFloat],
			["Number.parseInt", Number.parseInt],
			["Number.toString", Number.toString],
			["Number.toFixed", Number.toFixed],
			["Number.toExponential", Number.toExponential],
			["Number.toPrecision", Number.toPrecision],
			["Number.valueOf", Number.valueOf],
